version: "3"
services:
    db:
        build: ./mysql
        restart: always
        container_name: db
        platform: linux/x86_64
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - /var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mysql
          MYSQL_DATABASE_HOST: db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    app:
        build: ./src
        container_name: app
        platform: linux/x86_64
        command: sh -c "sleep 20s; python3 ./process.py"
        links:
            - "db"
        depends_on:
          - db
